# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_auto_20170520_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
